//! WebAssembly entry module for the GraphLaw JSON-over-linear-memory ABI.
//!
//! The FFI shell ([`ffi`]) and the ABI metadata ([`abi_meta`]) are generated by
//! `ggen sync` from `ontologies/graphlaw-wasm.ttl` through the
//! rust-wasi-wasmex-pack (queries/ + templates/abi/). All behaviour lives in
//! the safe, native-testable `graphlaw::abi`; the only `unsafe` in this crate
//! is the pointer handling in the generated shell required to exchange
//! buffers with the host through linear memory.
//!
//! Protocol (all integers are wasm `i32`/`i64`):
//! 1. `gl_alloc(len) -> ptr` — host reserves `len` bytes and writes a UTF-8
//!    JSON request there.
//! 2. `gl_call(ptr, len) -> packed` — runs the request and consumes (frees)
//!    the request buffer. `packed = (out_ptr << 32) | out_len`.
//! 3. host reads `out_len` bytes at `out_ptr` (UTF-8 JSON), then
//!    `gl_free(out_ptr, out_len)`.
//!
//! A response is always JSON and never empty. The generated shell's
//! empty-response substitution branch is therefore dead code in this crate.
#![deny(missing_docs)]

/// Generated ABI metadata (limits, version, op and error-code tables),
/// rendered from ontologies/graphlaw-wasm.ttl; never edit by hand.
pub mod abi_meta;
/// Generated FFI shell (gl_alloc/gl_call/gl_free), rendered from
/// ontologies/graphlaw-wasm.ttl; never edit by hand.
pub mod ffi;

// Compile-time pins: the rendered limits (graphlaw-wasm.ttl -> abi_meta.rs)
// must equal graphlaw::abi, the single source of truth for the ABI limits.
const _: () = {
    assert!(abi_meta::MAX_REQUEST_BYTES == graphlaw::abi::MAX_REQUEST_BYTES);
    assert!(abi_meta::MAX_OUTSTANDING_BYTES == graphlaw::abi::MAX_OUTSTANDING_ALLOC_BYTES);
    assert!(abi_meta::MAX_JSON_DEPTH == graphlaw::abi::MAX_JSON_DEPTH);
    assert!(abi_meta::ABI_VERSION == graphlaw::abi::ABI_VERSION);
};

#[cfg(test)]
mod contract {
    use super::{abi_meta, ffi};

    /// The generated abi_meta tables mirror src/registry.rs, the single
    /// source of truth for the wire surface.
    #[test]
    fn abi_meta_mirrors_registry_ops() {
        assert_eq!(abi_meta::OPS, graphlaw::registry::op_names());
    }

    #[test]
    fn abi_meta_mirrors_registry_error_codes() {
        let codes: Vec<&str> = graphlaw::registry::REFUSAL_CODES
            .iter()
            .map(|row| row.code)
            .collect();
        assert_eq!(abi_meta::ERROR_CODES, codes.as_slice());
    }

    /// The generated shell routes through graphlaw::abi: no handle_request
    /// hook, no local limit constants (W641c conflict rows 1-3).
    #[test]
    fn shell_routes_through_graphlaw_abi() {
        let response = unsafe { ffi::call_buf(core::ptr::null_mut(), 0) };
        assert_eq!(response, graphlaw::abi::missing_buffer_response());
        let oversized_len = u32::MAX;
        let oversized = unsafe { ffi::call_buf(core::ptr::dangling_mut::<u8>(), oversized_len) };
        assert_eq!(
            oversized,
            graphlaw::abi::limit_response(
                "request_bytes",
                oversized_len as usize,
                graphlaw::abi::MAX_REQUEST_BYTES
            )
        );
        assert!(!response.is_empty() && !oversized.is_empty());
    }
}
